<?php
/*
 +-------------------------------------------------------------------------+
 | Copyright (C) 2004-2026 The Cacti Group                                 |
 |                                                                         |
 | This program is free software; you can redistribute it and/or           |
 | modify it under the terms of the GNU General Public License             |
 | as published by the Free Software Foundation; either version 2          |
 | of the License, or (at your option) any later version.                  |
 +-------------------------------------------------------------------------+
 | Cacti: The Complete RRDtool-based Graphing Solution                     |
 +-------------------------------------------------------------------------+
*/

declare(strict_types = 1);

/*
 * The supported PHP floor is written down in four places. They drifted once:
 * the constant said 8.3 while the installer still showed users 7.4 and the
 * generated platform check gated at 8.1.
 */

/**
 * CACTI_PHP_VERSION_MINIMUM without booting Cacti.
 */
function php_floor_constant(): string {
	$source = file_get_contents(dirname(__DIR__, 3) . '/include/global_constants.php');

	expect($source)->toBeString();
	expect(preg_match("/define\('CACTI_PHP_VERSION_MINIMUM',\s*'([^']+)'\)/", (string) $source, $m))->toBe(1);

	return $m[1];
}

it('declares one PHP floor across composer, the constant and the platform check', function (): void {
	$root     = dirname(__DIR__, 3);
	$floor    = php_floor_constant();
	$composer = json_decode((string) file_get_contents($root . '/composer.json'), true, flags: JSON_THROW_ON_ERROR);

	// ">=8.3" and "8.3.0" both have to describe the same release.
	$short = implode('.', array_slice(explode('.', $floor), 0, 2));

	expect($composer['require']['php'])->toBe('>=' . $short)
		->and($composer['config']['platform']['php'])->toBe($floor);
});

it('generates a platform check matching the declared floor', function (): void {
	$root = dirname(__DIR__, 3);

	// platform_check.php is generated by composer, and the project refuses
	// commits under include/vendor, so it only reflects the floor once the
	// tree has been installed.
	if (!is_dir($root . '/include/vendor/symfony/console')) {
		$this->markTestSkipped('include/vendor has not been installed');
	}

	$floor = php_floor_constant();
	$short = implode('.', array_slice(explode('.', $floor), 0, 2));
	$check = (string) file_get_contents($root . '/include/vendor/composer/platform_check.php');

	expect(preg_match('/PHP_VERSION_ID\s*>=\s*(\d+)/', $check, $m))->toBe(1);

	[$major, $minor] = array_map('intval', explode('.', $short));
	expect((int) $m[1])->toBe($major * 10000 + $minor * 100);
});

require_once dirname(__DIR__, 2) . '/Helpers/IsolatedProbe.php';

it('shows operators the declared floor rather than a stale literal', function (): void {
	$verdict = cacti_test_isolated_probe(dirname(__DIR__, 2) . '/fixtures/php_floor_probe.php');

	expect($verdict['reported'])->toBe($verdict['constant'])
		->and($verdict['reported'])->toBe(php_floor_constant());
});
