repos:
  - repo: local
    hooks:
      - id: lintcheck
        name: PHP Lint Checking
        entry: sh tests/tools/pre-commit-check.sh lint
        language: system
        types: [php]
        always_run: true

      - id: phpcsfixer
        name: PHP CS Fixer Validation
        entry: sh tests/tools/pre-commit-check.sh phpcsfixer
        language: system
        types: [php]
        always_run: true

      - id: phpstan
        name: PHPStan Validation
        entry: sh tests/tools/pre-commit-check.sh phpstan
        language: system
        types: [php]
        always_run: true
