repos:
  - repo: local
    hooks:
      - id: repository-guards
        name: Repository commit guards
        entry: sh tests/tools/pre-commit-check.sh guards
        language: system
        pass_filenames: false
        always_run: true

      - id: lintcheck
        name: PHP Lint Checking
        entry: sh tests/tools/pre-commit-check.sh lint
        language: system
        types: [php]

      - id: phpcsfixer
        name: PHP CS Fixer Validation
        entry: sh tests/tools/pre-commit-check.sh phpcsfixer
        language: system
        types: [file]
        files: '(\.php$|^composer\.json$)'
        pass_filenames: false

      - id: phpstan
        name: PHPStan Validation
        entry: sh tests/tools/pre-commit-check.sh phpstan
        language: system
        types: [file]
        files: '(\.php$|^composer\.json$|^phpstan.*\.neon$)'
        pass_filenames: false
