---
extends: default
rules:
  line-length:
    max: 200
    level: warning
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
    level: warning
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  trailing-spaces: enable
