#!/usr/bin/env bash
#
# +-------------------------------------------------------------------------+
# | Copyright (C) 2004-2023 The Cacti Group                                 |
# |                                                                         |
# | This program is free software; you can redistribute it and/or           |
# | modify it under the terms of the GNU General Public License             |
# | as published by the Free Software Foundation; either version 2          |
# | of the License, or (at your option) any later version.                  |
# |                                                                         |
# | This program is distributed in the hope that it will be useful,         |
# | but WITHOUT ANY WARRANTY; without even the implied warranty of          |
# | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           |
# | GNU General Public License for more details.                            |
# +-------------------------------------------------------------------------+
# | Cacti: The Complete RRDtool-based Graphing Solution                     |
# +-------------------------------------------------------------------------+
# | This code is designed, written, and maintained by the Cacti Group. See  |
# | about.php and/or the AUTHORS file for specific developer information.   |
# +-------------------------------------------------------------------------+
# | http://www.cacti.net/                                                   |
# +-------------------------------------------------------------------------+


SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

SUDO_USR=www-data
if [ -f "${SCRIPT_DIR}/.runuser" ]; then
	SUDO_USR=$(cat "{$SCRIPT_DIR}/.runuser");
fi
CAN_I_RUN_SUDO=$(sudo -n uptime 2>&1 | grep -E "(password|load)" | wc -l)

SUDO_CMD=
if [[ ${CAN_I_RUN_SUDO} != 0 ]]; then
	SUDO_CMD="sudo -u ${SUDO_USR} "
fi

${SUDO_CMD}php -q $@
